# STAT 6430
# Day 7 -- R
#
# Some hodge, less podge -- it's multiple regression!!
#
#
# On each of 20 lakes, wilderness managers have
# data on the size of the fish catch (the response)
# the number of residents, and the size of the lake.
#
fish01 = read.csv("fish01.csv", header = TRUE)
View(fish01)  # Pops up table version of fish01.
#
# Start with a plot of the data
#
plot(fish01,pch=20,cex=.2)  # Matrix plot in this case
#
fish01.lm <- lm(catch ~ residents+size, data=fish01)
#
# A summary of the values generated by lm:
#
summary(fish01.lm)
#
# It's interesting to see what we get from 
# using the individual variables
#
fish01a.lm <- lm(catch ~ residents, data=fish01)
summary(fish01a.lm)
#
fish01b.lm <- lm(catch ~ size, data=fish01)
summary(fish01b.lm)

# A second version of the fish data includes information
# on the size of the fish catch (the response),
# the number of residents, the size of the lake,
# and the season (time of year)
#
fish02 = read.csv("fish02.csv", header = TRUE)
#
plot(fish02,pch=20,cex=.2)
#

fish02.lm <- lm(catch~residents+size+season, data=fish02)
# Or: fish02.lm <- lm(catch~., data=fish) 
#
# A summary of the values generated by lm:
#
summary(fish02.lm)
#
# The "leaps" package makes available the "regsubsets" function that
# will give the best model for different numbers of variables:
install.packages("leaps")
library(leaps)

# regsubsets gives each size model that has the smallest RSS,
# residual sum of squares (aka SSE)
regsub.fish <- regsubsets(catch~., data=fish02)
summary(regsub.fish)

# Here are the RSS's for each model:
summary(regsub.fish)$rss

# There are other criteria that are used for model selection
#
summary(regsub.fish)$rsq    # R^2
summary(regsub.fish)$adjr2  # adjusted R^2
summary(regsub.fish)$cp     # Mallow's C_p (smaller is better)
summary(regsub.fish)$bic    # Bayes Information Criterion (negative OK)

names(summary(regsub.fish))

# The regsubsets function can also perform forward and backward
# stepwise selection:
regsub.fishfor <- regsubsets(catch~., data=fish02, method="forward")
summary(regsub.fishfor)

regsub.fishback <- regsubsets(catch~., data=fish02, method="backward")
summary(regsub.fishback)

# Partial F-Test: This test's a full regression model containing
# all variables against a partial model containing a subset of 
# variables.  The null hypothesis is that both models fit the 
# data equally well, the alternative is that the full model is
# superior.  

fish.lmpart <- lm(catch ~ residents+size, data=fish02)
fish.lmfull <- lm(catch ~ ., data=fish02)
anova(fish.lmpart,fish.lmfull)

# Here p = 0.1622, which does not imply that the full model is
# superior to the partial model.  This test does not contradict
# our earlier observations, although it is not the usual use of a hypothesis
# test, because *not* rejecting the null is providing the evidence
# we're looking for.  (Note that rejecting the null implies that there
# are useful variables in the full model that are not in the partial
# model.)


# Team Questions:
# 1. Upload the file "cruise01.csv" into R.  This data set contains 
#    records from 158 cruise ships, including crew size (the response
#    variable for this discussion) and six quantitative variables.
# 2. Make a scatter plot matrix of the data.
# 3. Use the methods described above to which linear linear models
#    seem to best fit this data.
# 4. Test your models with cross validation: Select 58 random records,
#    and develop each model based on this subset.  Then use your models to
#    compute the MSE's when predicting for the remaining 100 records.

cruise_data<-read.csv("cruise01.csv")

plot(cruise_data)

regsub_cruise <- regsubsets(crew~., data=cruise_data)
summary(regsub_cruise)
